run:
  concurrency: 4

  deadline: 5m

  issues-exit-code: 2

  go: '1.19'

linters-settings:
  dupl:
    threshold: 100
  gofmt:
    format-args: ["-s", "-d", "-e", "-extra", "-gap", "-local", ".", "-style", "{Indent: tab, Tabwidth: 4}"]
  govet:
    check-shadowing: true
  gocyclo:
    min-complecity: 10

linters:
  disable-all: true
  enable:
    - dupl
    - errcheck
    - gocyclo
    - gofmt
    - govet
